### ISSUE TITLE
plugin.fal_ttnews.mode not working

### ISSUE THREAD

**Issue by MrMooky** [MaxServ/t3ext-fal_ttnews#7]
I'm trying catch the reference title of attached media fields. I have access to the title field, which works as expected. But when I attach a picture to the media FAL of a news entry and change the title of the file, I get no output.

![screen shot 2015-10-13 at 11 57 00 am](https://cloud.githubusercontent.com/assets/3603346/10451613/8b10a06a-71a1-11e5-92bc-ee8ef02b663e.png)

title output is "Sanierung der Vorklä...". When I enter something (like "Test 123"), the output does not change.

Is this a common bug?

**Comment by derhecht** [comment]
You're right, this does not work. With https://github.com/MaxServ/t3ext-fal_ttnews/pull/8 mode will corrected at all and also take core of this override (after actualization in a few minutes).

**Comment by derhecht** [comment]
Keep in mind to setup mode = 2 after this https://github.com/MaxServ/t3ext-fal_ttnews/pull/8 is merged it will work as expected.

**Comment by Tuurlijk** [comment]
Code was merged, so should work as expected now.
